base:
  db: mongodb://localhost/portal
  secret: your_secret
  port: 80
  host: http://127.0.0.1
  cspReportUrl: /
  urlPrefix:
  cdnPrefix:
  ssoUrl: http://127.0.0.1:20212   # false to enable debug mode and bypass SSO
  api:
    credential:
      username: foo
      password: bar
  match:
    initialMaps:
      - 1
      - 2
      - 3
  mq:
    vhosts:
      /:
        connection:
          hostname: localhost
          user: guest
          password: guest
        queues:
          - gomoku_compile
          - gomoku_judge
        publications:
          compile:
            queue: gomoku_compile
          judge:
            queue: gomoku_judge
