base:
  db: mongodb://localhost/portal
  secret: your_secret
  port: 80
  host: 127.0.0.1:80
  cspReportUrl: /
  urlPrefix: ''
  cdnPrefix: ''
  ssoUrl: http://127.0.0.1:20212   # false to enable debug mode and bypass SSO
  scoreboard:
    cacheDuration: 600000     # 10 minutes
  api:
    credential:
      username: foo
      password: bar
  compile:
    limits:
      sizeOfCode: 1048576     # 1 MB
      sizeOfBin: 1048576      # 1 MB
      sizeOfText: 102400      # 100 KB
      submitInterval: 86400000 # 1 day
      minSubmitInterval: 60000 # 1 minute
  match:
    rules:
      moveTimeout: 5000       # 5 s
      roundTimeout: 180000    # 180 s
      memoryLimit: 367001600  # 350 MB
      width: 20
      height: 20
      winningStones: 5
    openings:
      - opening1
      - opening2
      - opening3
  profiling:
    eventBus: false
    addMatches: false
  mq:
    vhosts:
      /:
        connection:
          hostname: localhost
          user: guest
          password: guest
        queues:
          - gomoku_compile
          - gomoku_judge
        publications:
          compile:
            queue: gomoku_compile
          judge:
            queue: gomoku_judge
